# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r
r:
  - release
sudo: false
cache: packages

install:
  - R -e 'devtools::install_deps(dep = TRUE)'

script:
  - R CMD build .
  - R CMD check --no-tests *tar.gz
  - Rscript tests/testthat/monitory_files.R -d tests/testthat/target_dir3 -l tests/testthat/log_file.txt -t 120 &
  - Rscript run_tests.R

after_success:
  - Rscript -e 'covr::codecov()'
