# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r
r:
  - release
sudo: false
cache: packages

install:
  - R -e 'devtools::install_deps(dep = TRUE)'
  - R CMD INSTALL roxygen2

script:
  - R CMD build .
  - PKG_FILE_NAME=$(ls -1t *.tar.gz | head -n 1)
  - R CMD check --no-tests $PKG_FILE_NAME
  - Rscript tests/testthat/monitor_files.R -d tests/testthat/target_dir3 -l tests/testthat/log_file.txt -t 120 &
  - Rscript run_tests.R

after_success:
  - Rscript -e 'covr::codecov()'
